In [ ]:
import pandas as pd

In [ ]:
clinical = pd.read_csv('../Data/luad_clinical_data.tsv', sep="\t")
expression = pd.read_csv('../Data/luad_mrna_data.txt', sep="\t")

clinical.head()

,Study ID,Patient ID,Sample ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Aneuploidy Score,Buffa Hypoxia Score,Cancer Type,TCGA PanCanAtlas Cancer Type Acronym,...,Tumor Break Load,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site,Tissue Source Site Code,TMB (nonsynonymous),Tumor Disease Anatomic Site,Tumor Type,Patient Weight,Winter Hypoxia Score
0,luad_tcga_pan_can_atlas_2018,TCGA-05-4244,TCGA-05-4244-01,70.0,STAGE IV,6TH,17.0,11.0,Non-Small Cell Lung Cancer,LUAD,...,98.0,No,Yes,Indivumed,5,6.400000,Lung,Lung Adenocarcinoma (NOS),NaN,20.0
1,luad_tcga_pan_can_atlas_2018,TCGA-05-4249,TCGA-05-4249-01,67.0,STAGE IB,6TH,24.0,-27.0,Non-Small Cell Lung Cancer,LUAD,...,29.0,No,Yes,Indivumed,5,10.000000,Lung,Lung Adenocarcinoma (NOS),NaN,-26.0
2,luad_tcga_pan_can_atlas_2018,TCGA-05-4250,TCGA-05-4250-01,79.0,STAGE IIIA,6TH,17.0,29.0,Non-Small Cell Lung Cancer,LUAD,...,81.0,No,Yes,Indivumed,5,10.500000,Lung,Lung Adenocarcinoma (NOS),NaN,32.0
3,luad_tcga_pan_can_atlas_2018,TCGA-05-4382,TCGA-05-4382-01,68.0,STAGE IB,6TH,22.0,19.0,Non-Small Cell Lung Cancer,LUAD,...,226.0,No,Yes,Indivumed,5,51.733333,Lung,"Lung Adenocarcinoma, Mixed Subtype",NaN,34.0
4,luad_tcga_pan_can_atlas_2018,TCGA-05-4384,TCGA-05-4384-01,66.0,STAGE IIIA,6TH,1.0,-37.0,Non-Small Cell Lung Cancer,LUAD,...,6.0,No,Yes,Indivumed,5,3.966667,Lung,"Lung Adenocarcinoma, Mixed Subtype",NaN,-24.0

In [ ]:
expression.head()

,STUDY_ID,SAMPLE_ID,EGFR,KRAS,ALK,ERBB2,CD274
0,luad_tcga_pan_can_atlas_2018,TCGA-05-4244-01,2347.770,1962.13,6.6323,10643.50,261.1050
1,luad_tcga_pan_can_atlas_2018,TCGA-05-4249-01,1615.540,4618.15,7.0830,8495.47,67.6109
2,luad_tcga_pan_can_atlas_2018,TCGA-05-4250-01,792.154,4723.20,1.6580,7639.89,404.2110
3,luad_tcga_pan_can_atlas_2018,TCGA-05-4382-01,626.496,1599.75,9.3329,9857.66,117.2590
4,luad_tcga_pan_can_atlas_2018,TCGA-05-4384-01,582.156,1329.26,5.4979,12105.70,32.3763

In [ ]:
clinical.columns

Index(['Study ID', 'Patient ID', 'Sample ID', 'Diagnosis Age',
       'Neoplasm Disease Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Publication Version Type',
       'Aneuploidy Score', 'Buffa Hypoxia Score', 'Cancer Type',
       'TCGA PanCanAtlas Cancer Type Acronym', 'Cancer Type Detailed',
       'Last Communication Contact from Initial Pathologic Diagnosis Date',
       'Birth from Initial Pathologic Diagnosis Date',
       'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value',
       'Disease Free (Months)', 'Disease Free Status',
       'Months of disease-specific survival',
       'Disease-specific Survival status', 'Ethnicity Category',
       'Form completion date', 'Fraction Genome Altered',
       'Genetic Ancestry Label', 'Neoplasm Histologic Grade',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'Informed consent verified', 'In PanCan Pathway Analysis',
       'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count',
       'New Neoplasm Event Post Initial Therapy Indicator', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status',
       'Other Patient ID',
       'American Joint Committee on Cancer Metastasis Stage Code',
       'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Tumor Stage Code',
       'Person Neoplasm Cancer Status', 'Progress Free Survival (Months)',
       'Progression Free Status', 'Primary Lymph Node Presentation Assessment',
       'Prior Diagnosis', 'Race Category', 'Radiation Therapy',
       'Ragnum Hypoxia Score', 'Number of Samples Per Patient', 'Sample Type',
       'Sex', 'Somatic Status', 'Subtype', 'Tumor Break Load',
       'Tissue Prospective Collection Indicator',
       'Tissue Retrospective Collection Indicator', 'Tissue Source Site',
       'Tissue Source Site Code', 'TMB (nonsynonymous)',
       'Tumor Disease Anatomic Site', 'Tumor Type', 'Patient Weight',
       'Winter Hypoxia Score'],
      dtype='object')

In [ ]:
clinical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 63 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   Study ID                                                                                     566 non-null    object
 1   Patient ID                                                                                   566 non-null    object
 2   Sample ID                                                                                    566 non-null    object
 3   Diagnosis Age                                                                                495 non-null    float64
 4   Neoplasm Disease Stage American Joint Committee on Cancer Code                               512 non-null    object
 5   American Joint Committee on Cancer Publication Version Type                                  493 non-null    object
 6   Aneuploidy Score                                                                             501 non-null    float64
 7   Buffa Hypoxia Score                                                                          510 non-null    float64
 8   Cancer Type                                                                                  566 non-null    object
 9   TCGA PanCanAtlas Cancer Type Acronym                                                         566 non-null    object
 10  Cancer Type Detailed                                                                         566 non-null    object
 11  Last Communication Contact from Initial Pathologic Diagnosis Date                            392 non-null    float64
 12  Birth from Initial Pathologic Diagnosis Date                                                 483 non-null    float64
 13  Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                       495 non-null    float64
 14  Disease Free (Months)                                                                        301 non-null    float64
 15  Disease Free Status                                                                          304 non-null    object
 16  Months of disease-specific survival                                                          505 non-null    float64
 17  Disease-specific Survival status                                                             478 non-null    object
 18  Ethnicity Category                                                                           390 non-null    object
 19  Form completion date                                                                         514 non-null    object
 20  Fraction Genome Altered                                                                      500 non-null    float64
 21  Genetic Ancestry Label                                                                       560 non-null    object
 22  Neoplasm Histologic Grade                                                                    0 non-null      float64
 23  Neoadjuvant Therapy Type Administered Prior To Resection Text                                514 non-null    object
 24  ICD-10 Classification                                                                        514 non-null    object
 25  International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code  514 non-null    object
 26  International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code       514 non-null    object
 27  Informed consent verified                                                                    514 non-null    object
 28  In PanCan Pathway Analysis                                                                   566 non-null    object
 29  MSI MANTIS Score                                                                             564 non-null    float64
 30  MSIsensor Score                                                                              565 non-null    float64
 31  Mutation Count                                                                               561 non-null    float64
 32  New Neoplasm Event Post Initial Therapy Indicator                                            449 non-null    object
 33  Oncotree Code                                                                                566 non-null    object
 34  Overall Survival (Months)                                                                    505 non-null    float64
 35  Overall Survival Status                                                                      514 non-null    object
 36  Other Patient ID                                                                             514 non-null    object
 37  American Joint Committee on Cancer Metastasis Stage Code                                     510 non-null    object
 38  Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                    513 non-null    object
 39  American Joint Committee on Cancer Tumor Stage Code                                          514 non-null    object
 40  Person Neoplasm Cancer Status                                                                421 non-null    object
 41  Progress Free Survival (Months)                                                              505 non-null    float64
 42  Progression Free Status                                                                      514 non-null    object
 43  Primary Lymph Node Presentation Assessment                                                   0 non-null      float64
 44  Prior Diagnosis                                                                              514 non-null    object
 45  Race Category                                                                                449 non-null    object
 46  Radiation Therapy                                                                            467 non-null    object
 47  Ragnum Hypoxia Score                                                                         510 non-null    float64
 48  Number of Samples Per Patient                                                                566 non-null    int64
 49  Sample Type                                                                                  566 non-null    object
 50  Sex                                                                                          514 non-null    object
 51  Somatic Status                                                                               566 non-null    object
 52  Subtype                                                                                      502 non-null    object
 53  Tumor Break Load                                                                             513 non-null    float64
 54  Tissue Prospective Collection Indicator                                                      507 non-null    object
 55  Tissue Retrospective Collection Indicator                                                    507 non-null    object
 56  Tissue Source Site                                                                           566 non-null    object
 57  Tissue Source Site Code                                                                      566 non-null    object
 58  TMB (nonsynonymous)                                                                          566 non-null    float64
 59  Tumor Disease Anatomic Site                                                                  514 non-null    object
 60  Tumor Type                                                                                   566 non-null    object
 61  Patient Weight                                                                               0 non-null      float64
 62  Winter Hypoxia Score                                                                         510 non-null    float64
dtypes: float64(21), int64(1), object(41)
memory usage: 278.7+ KB

In [ ]:
clinical.shape

(566, 63)

In [ ]:
clinical.describe()

In [ ]:
expression.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STUDY_ID   566 non-null    object
 1   SAMPLE_ID  566 non-null    object
 2   EGFR       510 non-null    float64
 3   KRAS       510 non-null    float64
 4   ALK        510 non-null    float64
 5   ERBB2      510 non-null    float64
 6   CD274      510 non-null    float64
dtypes: float64(5), object(2)
memory usage: 31.1+ KB

In [ ]:
expression.describe()

               EGFR          KRAS         ALK          ERBB2        CD274
count    510.000000    510.000000  510.000000     510.000000   510.000000
mean    1630.825665   1714.645598   15.002787    7780.428149   123.621458
std     2487.644757   1770.907305   56.915949   14424.544639   193.676599
min       12.516800    483.732000    0.000000     353.440000     1.071200
25%      539.147000   1059.487500    1.817725    4308.517500    30.506025
50%      994.597000   1367.535000    4.395750    6104.520000    62.047850
75%     1766.047500   1850.927500    9.063525    8446.007500   116.575250
max    24089.100000  29832.800000  836.087000  262936.000000  1650.700000

In [ ]:
clinical.isnull().sum()

Study ID                                                            0
Patient ID                                                          0
Sample ID                                                           0
Diagnosis Age                                                      71
Neoplasm Disease Stage American Joint Committee on Cancer Code     54
                                                                 ...
TMB (nonsynonymous)                                                 0
Tumor Disease Anatomic Site                                        52
Tumor Type                                                          0
Patient Weight                                                    566
Winter Hypoxia Score                                               56
Length: 63, dtype: int64

In [ ]:
expression.isnull().sum()

STUDY_ID      0
SAMPLE_ID     0
EGFR         56
KRAS         56
ALK          56
ERBB2        56
CD274        56
dtype: int64

In [ ]:
clinical.to_csv("../Data/luad_clinical_data.csv", index=False)

In [ ]:
expression.to_csv("../Data/luad_mrna_data.csv", index=False)

In [ ]:
clinical.duplicated().sum()

np.int64(0)

In [ ]:
expression.duplicated().sum()

np.int64(0)

In [ ]:
clinical.columns = clinical.columns.str.lower()

In [ ]:
clinical.columns = clinical.columns.str.replace(" ", "_").str.replace("(", "").str.replace(")", "")

In [ ]:
clinical.head()

In [ ]:
clinical_clean = clinical[[
    'patient_id',
    'sample_id',
    'diagnosis_age',
    'neoplasm_disease_stage_american_joint_committee_on_cancer_code',
    'overall_survival_months',
    'overall_survival_status',
    'mutation_count',
    'msi_mantis_score',
    'tmb_nonsynonymous',
    'buffa_hypoxia_score'
]]

In [ ]:
clinical_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 10 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   patient_id                                                      566 non-null    object
 1   sample_id                                                       566 non-null    object
 2   diagnosis_age                                                   495 non-null    float64
 3   neoplasm_disease_stage_american_joint_committee_on_cancer_code  512 non-null    object
 4   overall_survival_months                                         505 non-null    float64
 5   overall_survival_status                                         514 non-null    object
 6   mutation_count                                                  561 non-null    float64
 7   msi_mantis_score                                                564 non-null    float64
 8   tmb_nonsynonymous                                               566 non-null    float64
 9   buffa_hypoxia_score                                             510 non-null    float64
dtypes: float64(6), object(4)
memory usage: 44.3+ KB

In [ ]:
clinical_clean.isnull().sum()

patient_id                                                         0
sample_id                                                          0
diagnosis_age                                                     71
neoplasm_disease_stage_american_joint_committee_on_cancer_code    54
overall_survival_months                                           61
overall_survival_status                                           52
mutation_count                                                     5
msi_mantis_score                                                   2
tmb_nonsynonymous                                                  0
buffa_hypoxia_score                                               56
dtype: int64

In [ ]:
clinical_clean = clinical_clean.dropna(
    subset=['overall_survival_months', 'overall_survival_status']
)

In [ ]:
clinical_clean['survival_status_binary'] = clinical_clean['overall_survival_status'].apply(
    lambda x: 1 if 'DECEASED' in str(x).upper() else 0
)

In [ ]:
clinical_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 505 entries, 0 to 565
Data columns (total 11 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   patient_id                                                      505 non-null    object
 1   sample_id                                                       505 non-null    object
 2   diagnosis_age                                                   505 non-null    float64
 3   neoplasm_disease_stage_american_joint_committee_on_cancer_code  505 non-null    object
 4   overall_survival_months                                         505 non-null    float64
 5   overall_survival_status                                         505 non-null    object
 6   mutation_count                                                  505 non-null    float64
 7   msi_mantis_score                                                505 non-null    float64
 8   tmb_nonsynonymous                                               505 non-null    float64
 9   buffa_hypoxia_score                                             505 non-null    float64
 10  survival_status_binary                                          505 non-null    int64
dtypes: float64(6), int64(1), object(4)
memory usage: 47.3+ KB

In [ ]:
clinical_clean.rename(columns={
    'neoplasm_disease_stage_american_joint_committee_on_cancer_code': 'cancer_stage'
}, inplace=True)

In [ ]:
clinical_clean.head(3)
clinical_clean.describe()

In [ ]:
clinical_clean.head(3)

,patient_id,sample_id,diagnosis_age,cancer_stage,overall_survival_months,overall_survival_status,mutation_count,msi_mantis_score,tmb_nonsynonymous,buffa_hypoxia_score,survival_status_binary
0,TCGA-05-4244,TCGA-05-4244-01,70.0,STAGE IV,0.000000,0:LIVING,192.0,0.2886,6.4,11.0,0
1,TCGA-05-4249,TCGA-05-4249-01,67.0,STAGE IB,50.070684,0:LIVING,300.0,0.2807,10.0,-27.0,0
2,TCGA-05-4250,TCGA-05-4250-01,79.0,STAGE IIIA,3.978039,1:DECEASED,312.0,0.3059,10.5,29.0,1

1. mutation count:Total number of genetic mutations found in a tumor
Higher mutation count = more unstable tumor
-What we can analyze:
Does higher mutation count → worse survival?
Or does it respond better to treatment?
-Business Insight(BI):
“Patients with higher mutation counts may require more aggressive or targeted therapies.”

2. MSI MANTIS Score
Measures microsatellite instability (MSI) — a type of DNA repair failure
High MSI score → defective repair system
High MSI patients often respond very well to immunotherapy
-BI: “MSI-high patients represent a high-value group for immunotherapy treatments.”

3. TMB (Tumor Mutational Burden - nonsynonymous)
Number of mutations that actually change proteins
Not all mutations matter.
Some = harmless
Some = change protein → affect tumor behavior
-TMB counts the important ones
High TMB → more abnormal proteins
Makes tumor more visible to immune system
Often linked to better response to immunotherapy
BI:“High TMB patients are strong candidates for immune-based treatments.”

4. Buffa Hypoxia Score
Measures how low-oxygen (hypoxic) the tumor environment is
Tumors often grow in low oxygen areas
Low oxygen → more aggressive cancer
Harder to treat
High score = more hypoxia = worse conditions
Hypoxic tumors:Grow faster, Resist treatment
BI:“Patients with high hypoxia scores may show reduced treatment effectiveness and poorer survival outcomes.”

| Biomarker      | What it tells you   |
| -------------- | ------------------- |
| Mutation Count | Tumor instability   |
| MSI Score      | DNA repair failure  |
| TMB            | Important mutations |
| Hypoxia Score  | Tumor environment   |

In [ ]:
expression.columns = expression.columns.str.lower()
expression.head(5)

,study_id,sample_id,egfr,kras,alk,erbb2,cd274
0,luad_tcga_pan_can_atlas_2018,TCGA-05-4244-01,2347.770,1962.13,6.6323,10643.50,261.1050
1,luad_tcga_pan_can_atlas_2018,TCGA-05-4249-01,1615.540,4618.15,7.0830,8495.47,67.6109
2,luad_tcga_pan_can_atlas_2018,TCGA-05-4250-01,792.154,4723.20,1.6580,7639.89,404.2110
3,luad_tcga_pan_can_atlas_2018,TCGA-05-4382-01,626.496,1599.75,9.3329,9857.66,117.2590
4,luad_tcga_pan_can_atlas_2018,TCGA-05-4384-01,582.156,1329.26,5.4979,12105.70,32.3763

In [ ]:

clinical_clean.duplicated(subset=['patient_id']).sum()

clinical_clean = clinical_clean.drop_duplicates(subset=['patient_id'])

In [ ]:
expression.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   study_id   566 non-null    object
 1   sample_id  566 non-null    object
 2   egfr       566 non-null    float64
 3   kras       566 non-null    float64
 4   alk        566 non-null    float64
 5   erbb2      566 non-null    float64
 6   cd274      566 non-null    float64
dtypes: float64(5), object(2)
memory usage: 31.1+ KB

In [ ]:
expression.describe()

               egfr          kras         alk          erbb2        cd274
count    566.000000    566.000000  566.000000     566.000000   566.000000
mean    1567.877246   1680.302500   13.953328    7614.613915   117.529370
std     2368.790026   1684.053785   54.114670   13700.208320   184.746730
min       12.516800    483.732000    0.000000     353.440000     1.071200
25%      585.899750   1110.615000    2.149300    4565.052500    32.740425
50%      994.597000   1367.535000    4.395750    6104.520000    62.047850
75%     1626.265000   1802.812500    8.030750    8012.362500   109.018500
max    24089.100000  29832.800000  836.087000  262936.000000  1650.700000

In [ ]:
set(clinical_clean['sample_id']).intersection(set(expression['sample_id']))

In [ ]:
expression['sample_id'].head()

0    TCGA-05-4244-01
1    TCGA-05-4249-01
2    TCGA-05-4250-01
3    TCGA-05-4382-01
4    TCGA-05-4384-01
Name: sample_id, dtype: object

In [ ]:

clinical_clean['sample_id'].duplicated().sum()
expression['sample_id'].duplicated().sum()

np.int64(0)

In [ ]:
merged_df = clinical_clean.merge(
    expression,
    on='sample_id',
    how='inner'
)

In [ ]:

merged_df.shape

(505, 17)

In [ ]:
merged_df.isnull().sum()

patient_id                 0
sample_id                  0
diagnosis_age              0
cancer_stage               0
overall_survival_months    0
overall_survival_status    0
mutation_count             0
msi_mantis_score           0
tmb_nonsynonymous          0
buffa_hypoxia_score        0
survival_status_binary     0
study_id                   0
egfr                       0
kras                       0
alk                        0
erbb2                      0
cd274                      0
dtype: int64

#this is data cleaning and merging datasets